In [1]:
import numpy as np 
import scipy 
import scipy.linalg  

In [2]:
A = np.array([ [1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print(P)
print(L)
print(U)

print(np.dot(P.transpose(), A) - np.dot(L, U))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
L = np.array([ [1, 0, 0], [0.25, 1, 0], [0.5, -0.4, 1]])
U = np.array([ [4, 28, 73], [0, -5, -15.25], [0, 0, -21.6]])
A = np.dot(L, U)
P, L, U = scipy.linalg.lu(A)

print("det A = ", np.linalg.det(A))
print("A = ", A)
print("P = ", P)
print("L = ", L)
print("U = ", U)

B = np.array([4, 1, 7])
np.linalg.solve(A, B)

det A =  432.00000000000017
A =  [[ 4. 28. 73.]
 [ 1.  2.  3.]
 [ 2. 16. 21.]]
P =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L =  [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U =  [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


array([ 0.28240741,  0.70601852, -0.23148148])